#!/bin/bash
yum install -y dialog 1>/dev/null
export NCURSES_NO_UTF8_ACS=1
login=""
ip=""
exec 3>&1
dialog --separate-widget $'\n' --ok-label "Submit" \
          --backtitle "Welcome to the centos server integration wizard in the active directory domain  " \
          --title "your_domain.com" \
          --form "Please before to start make sure that you have copied the kerberos.txt file in the /root/ path" \
15 70 0 \
        "AD IP address      :" 1 1 "$ip"           1 22 40 0 \
        "Administrator Login:" 2 1 "$login"        2 22 40 0 \
2>&1 1>&3 | {
  read -r ip
  read -r login
#-----------------------------------------------------------------------------------------------------------------------
retval=$?
if [ $retval == 0 ]; then
   echo $retval > /root/retval
   echo $ip > /root/ip
   echo $login > /root/login
else
   exit 1
fi
}
exec 3>&-

add_server() {
echo "$(tput setab 4)$(tput setaf 7) ___________________________________________________________"
echo " Downloading and installing packages                        "
echo "____________________________________________________________"
yum -y install ntp  1>/dev/null
echo " NTP.....................................................OK "

yum -y install  authconfig 1>/dev/null
echo " authconfig..............................................OK "

yum -y install -y krb5-workstation 1>/dev/null
echo " krb5-workstation........................................OK "

yum -y install  samba-common 1>/dev/null
echo " samba-common............................................OK "

yum -y install samba-winbind 1>/dev/null
echo " samba-winbind...........................................OK "

yum -y install samba-winbind-clients 1>/dev/null
echo " samba-winbind-clients...................................OK "

yum -y install pam_krb5 1>/dev/null
echo " pam_krb5................................................OK "

yum -y install sssd 1>/dev/null
echo " sssd....................................................OK "
yum -y install realmd 1>/dev/null
echo " realmd..................................................OK "
yum -y install oddjob 1>/dev/null
echo " oddjob..................................................OK "
yum -y install oddjob-mkhomedir 1>/dev/null
echo " oddjob-mkhomedir........................................OK "
yum -y install adcli 1>/dev/null
echo " adcli...................................................OK "
yum -y install samba-common-tools 1>/dev/null
echo " samba-common-tools......................................OK "
yum -y install openldap-clients 1>/dev/null
echo " openldap-clients........................................OK "
yum -y install policycoreutils-python 1>/dev/null
echo " policycoreutils-python..................................OK "
echo "____________________________________________________________"
echo " Configuring ntp time synchronization with Active Directory "
echo "____________________________________________________________"
ntpdate $1




cp /etc/krb5.conf /etc/krb5.conf.default
sed  "s/AD_SERVER/${1}/" kerberos.txt > /etc/krb5.conf

echo " Verifying Kerberos Authentication.........................."
echo "____________________________________________________________"
kinit $2 && echo " you are successfully authenticated and you got your kerberos ticket "
echo "____________________________________________________________"
echo " Integrating with your_domain.com Active Directory Domain          "
echo "____________________________________________________________"
authconfig --disablecache --enablewinbind --enablewinbindauth --smbsecurity=ads --smbworkgroup=YOUR_DOMAIN --smbrealm=YOUR_DOMAIN.COM --enablewinbindusedefaultdomain --winbindtemplatehomedir=/home/YOUR_DOMAIN.COM/%U --winbindtemplateshell=/bin/bash --enablekrb5 --krb5realm=YOUR_DOMAIN.COM --enablekrb5kdcdns --enablekrb5realmdns --enablelocauthorize --enablemkhomedir --enablepamaccess --updateall 2>/dev/null
net ads join YOUR_DOMAIN.COM -U $2
echo " $(tput setab 4)Welcome to your_domain.com (tput sgr 0)"
echo "____________________________________________________________"
}

retval=$(cat /root/retval)
if [ $retval == 0 ];then
   ip=$(cat /root/ip)
   login=$(cat /root/login)
   rm /root/login
   rm /root/ip
   rm /root/retval
   add_server "$ip" "$login"

else
   exit 1
fi
